services:
  db:
    image: postgres:15
    volumes:
      - ./api/cm-data/:/var/lib/postgresql/data/pgdata
    env_file:
      - ./api/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

    restart:
      always
    ports:
      - 5432:5432
  #pgadmin:
  #  image: dpage/pgadmin4
  #  networks:
  #    - default
  #  env_file:
  #    - ./api/.env
  #  depends_on:
  #    - db
  #  ports:
  #    - 8080:80
  snort:
    build:
      context: .
      dockerfile: Dockerfile.snort-engine
    image: cm-snortengine
    tty: true
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: cm-api
    command: uvicorn api.src.main:app --root-path /api --host 0.0.0.0 --port 8000 --reload
    restart: always
    tty: true
    env_file:
      - ./api/.env
    volumes:
    - ./api:/code/api
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: cm-frontend
    restart: always
    tty: true
    ports:
      - "3000:80"
