# Build step #1: build the React front end
FROM node:16-alpine as build-step
COPY frontend /code
WORKDIR /code
ENV PATH /code/node_modules/.bin:$PATH
RUN yarn install --network-timeout 600000
RUN yarn build

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY frontend/default.conf /etc/nginx/conf.d/default.conf