services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: cm-api
    command: uvicorn api.src.main:app --root-path /api --host 0.0.0.0 --port 8000
    restart: always
    tty: true
    volumes:
    - ./api:/code/api
  client:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: cm-frontend
    restart: always
    tty: true
    ports:
      - "3000:80"
