FROM ubuntu:23.04

# Packages needed
RUN apt-get update
RUN apt-get install -y \
    python3.11 \
    python3-pip

#Fast API
WORKDIR /code

COPY api/requirements.txt /code/api/
RUN pip install --no-cache-dir --upgrade -r /code/api/requirements.txt
COPY ./api /code/api/
ENV PYTHONPATH "${PYTHONPATH}:/code/api/"

RUN ln -s /usr/local/lib/python3.11/dist-packages/usr/lib/libyara.so /usr/lib/libyara.so && ldconfig