FROM python:3.10

#Download yara



# Set up Fast API
WORKDIR /code

COPY /api/requirements.txt /code/api/
RUN pip install --no-cache-dir --upgrade -r /code/api/requirements.txt
COPY /api /code/api

#have to create a soft link to installed yara library
RUN ln -s /usr/local/lib/python3.10/site-packages/usr/local/lib/libyara.so /usr/local/lib/libyara.so && ldconfig
