services:
  #db:
  #  image: postgres:15
  #  volumes:
  #    - ./api/cm-data/:/var/lib/postgresql/data/pgdata
  #  env_file:
  #    - ./api/.env
  #  environment:
  #    - PGDATA=/var/lib/postgresql/data/pgdata
  #  restart:
  #    always
  #  ports:
  #    - 5432:5432
  #pgadmin:
  #  image: dpage/pgadmin4
  #  networks:
  #    - default
  #  env_file:
  #    - ./api/.env
  #  depends_on:
  #    - db
  #  ports:
  #    - 8080:80
  snort:
    build:
      context: .
      dockerfile: Dockerfile.snort-engine
    image: cm-snortengine
    tty: true
    expose:
    - "5000"
  api:
    build:
      context: ../api
      dockerfile: ../docker/Dockerfile.api
    command: /usr/venv/bin/uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    image: cm-api
    restart: always
    tty: true
    env_file:
      - ../api/.env
    volumes:
    - ../api:/code/api
    expose:
      - "8000"
    #depends_on:
    #  - db
  client:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    image: cm-frontend
    restart: always
    tty: true
    ports:
      - "3000:80"
    depends_on:
      - api
